---
- name: Stop Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Deallocate the virtual machine
    azure_rm_virtualmachine:
      resource_group: ansible-vm
      name: linuxtestansible
      allocated: no
      
      
To Start

---
- name: Start Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Start the virtual machine
    azure_rm_virtualmachine:
      resource_group: ansible-vm
      name: linuxtestansible
